import {
  type SchemaColumnChange,
  type SchemaColumnDefinition,
  type SchemaDiffJson,
  type SchemaTableDiff,
} from "./schema-diff-schema";
import {
  quoteIdentifier,
  quoteQualifiedTable,
  validateIdentifier,
  validateIdentifiers,
} from "../shared/identifiers";

export interface GenerateSchemaSqlOptions {
  transaction: boolean;
  includeDrops: boolean;
  onProgress?: (message: string) => void;
}

export interface GeneratedSchemaSqlResult {
  sql: string;
  summary: {
    tablesToCreate: number;
    tablesToDrop: number;
    columnsToAdd: number;
    columnsToAlter: number;
    columnsToDrop: number;
    primaryKeysToChange: number;
  };
}

export function buildSchemaSqlOutputPath(inputPath: string): string {
  return inputPath.endsWith(".json")
    ? inputPath.replace(/\.json$/i, ".sql")
    : `${inputPath}.sql`;
}

export function generateSchemaSqlScript(
  diff: SchemaDiffJson,
  options: GenerateSchemaSqlOptions,
): GeneratedSchemaSqlResult {
  const lines: string[] = [];
  const summary = {
    tablesToCreate: 0,
    tablesToDrop: 0,
    columnsToAdd: 0,
    columnsToAlter: 0,
    columnsToDrop: 0,
    primaryKeysToChange: 0,
  };

  lines.push("-- Generated by frg-data-diff");
  lines.push("-- Review this schema SQL carefully before executing it.");
  lines.push(`-- Schema diff format: ${diff.format}`);
  lines.push(`-- Generated at: ${diff.generatedAt}`);
  lines.push(`-- Source schema: ${diff.source.schema}`);
  lines.push(`-- Destination schema: ${diff.dest.schema}`);

  if (options.transaction) {
    lines.push("");
    lines.push("BEGIN;");
  }

  reportProgress(
    options.onProgress,
    `Generating schema SQL for ${diff.tables.length} table diff(s)...`,
  );

  for (const [tableIndex, tableDiff] of diff.tables.entries()) {
    const progressLabel = `[schema-sql ${tableIndex + 1}/${diff.tables.length}] ${tableDiff.schema}.${tableDiff.table}`;

    reportProgress(
      options.onProgress,
      `${progressLabel}: ${summarizeSchemaSqlWork(tableDiff, options)}`,
    );

    const statements = buildTableStatements(tableDiff, options, summary);
    if (statements.length === 0) {
      reportProgress(
        options.onProgress,
        `${progressLabel}: no SQL statements generated`,
      );
      continue;
    }

    reportProgress(
      options.onProgress,
      `${progressLabel}: generated ${statements.length} SQL statement(s)`,
    );

    lines.push("");
    lines.push(`-- ${tableDiff.schema}.${tableDiff.table}`);
    lines.push(...statements);
  }

  if (options.transaction) {
    lines.push("");
    lines.push("COMMIT;");
  }

  lines.push("");

  return {
    sql: lines.join("\n"),
    summary,
  };
}

function buildTableStatements(
  tableDiff: SchemaTableDiff,
  options: GenerateSchemaSqlOptions,
  summary: GeneratedSchemaSqlResult["summary"],
): string[] {
  validateIdentifier(tableDiff.schema, "schema name");
  validateIdentifier(tableDiff.table, "table name");
  const qualifiedTable = quoteQualifiedTable(tableDiff.schema, tableDiff.table);
  const statements: string[] = [];

  if (tableDiff.createTable) {
    statements.push(
      buildCreateTableStatement(
        tableDiff.schema,
        tableDiff.table,
        tableDiff.createTable.columns,
        tableDiff.createTable.primaryKey,
      ),
    );
    summary.tablesToCreate++;
    return statements;
  }

  if (tableDiff.dropTable) {
    if (options.includeDrops) {
      statements.push(`DROP TABLE IF EXISTS ${qualifiedTable};`);
      summary.tablesToDrop++;
    }
    return statements;
  }

  if (
    tableDiff.primaryKeyChange &&
    tableDiff.primaryKeyChange.from.length > 0
  ) {
    const constraintName =
      tableDiff.primaryKeyChange.dropConstraintName ??
      `${tableDiff.table}_pkey`;
    validateIdentifier(constraintName, "primary key constraint name");
    statements.push(
      `ALTER TABLE ${qualifiedTable} DROP CONSTRAINT IF EXISTS ${quoteIdentifier(constraintName)};`,
    );
    summary.primaryKeysToChange++;
  }

  for (const column of tableDiff.addColumns) {
    statements.push(
      `ALTER TABLE ${qualifiedTable} ADD COLUMN ${buildColumnDefinitionSql(column)};`,
    );
    summary.columnsToAdd++;
  }

  for (const columnChange of tableDiff.alterColumns) {
    statements.push(
      ...buildAlterColumnStatements(qualifiedTable, columnChange),
    );
    summary.columnsToAlter++;
  }

  if (options.includeDrops) {
    for (const column of tableDiff.dropColumns) {
      validateIdentifier(column.name, "drop column name");
      statements.push(
        `ALTER TABLE ${qualifiedTable} DROP COLUMN ${quoteIdentifier(column.name)};`,
      );
      summary.columnsToDrop++;
    }
  }

  if (tableDiff.primaryKeyChange && tableDiff.primaryKeyChange.to.length > 0) {
    validateIdentifiers(tableDiff.primaryKeyChange.to, "primary key column");
    statements.push(
      `ALTER TABLE ${qualifiedTable} ADD PRIMARY KEY (${tableDiff.primaryKeyChange.to.map(quoteIdentifier).join(", ")});`,
    );
    if (tableDiff.primaryKeyChange.from.length === 0) {
      summary.primaryKeysToChange++;
    }
  }

  return statements;
}

function buildCreateTableStatement(
  schema: string,
  table: string,
  columns: SchemaColumnDefinition[],
  primaryKey: string[],
): string {
  validateIdentifier(schema, "schema name");
  validateIdentifier(table, "table name");
  validateIdentifiers(
    columns.map((column) => column.name),
    "create column",
  );
  validateIdentifiers(primaryKey, "primary key column");

  const lines = columns.map(
    (column) => `  ${buildColumnDefinitionSql(column)}`,
  );
  if (primaryKey.length > 0) {
    lines.push(`  PRIMARY KEY (${primaryKey.map(quoteIdentifier).join(", ")})`);
  }

  return `CREATE TABLE ${quoteQualifiedTable(schema, table)} (\n${lines.join(",\n")}\n);`;
}

function buildColumnDefinitionSql(column: SchemaColumnDefinition): string {
  validateIdentifier(column.name, "column name");
  let definition = `${quoteIdentifier(column.name)} ${column.type}`;

  if (column.isGenerated && column.generationExpression) {
    definition += ` GENERATED ALWAYS AS (${column.generationExpression}) STORED`;
    return definition;
  }

  if (column.default !== null) {
    definition += ` DEFAULT ${column.default}`;
  }

  if (!column.nullable) {
    definition += " NOT NULL";
  }

  return definition;
}

function buildAlterColumnStatements(
  qualifiedTable: string,
  columnChange: SchemaColumnChange,
): string[] {
  const columnName = quoteIdentifier(columnChange.column);
  const statements: string[] = [];

  if (
    columnChange.from.isGenerated !== columnChange.to.isGenerated ||
    columnChange.from.generationExpression !==
      columnChange.to.generationExpression
  ) {
    statements.push(`ALTER TABLE ${qualifiedTable} DROP COLUMN ${columnName};`);
    statements.push(
      `ALTER TABLE ${qualifiedTable} ADD COLUMN ${buildColumnDefinitionSql(columnChange.to)};`,
    );
    return statements;
  }

  if (columnChange.from.type !== columnChange.to.type) {
    statements.push(
      `ALTER TABLE ${qualifiedTable} ALTER COLUMN ${columnName} TYPE ${columnChange.to.type};`,
    );
  }

  if (columnChange.from.default !== columnChange.to.default) {
    if (columnChange.to.default === null) {
      statements.push(
        `ALTER TABLE ${qualifiedTable} ALTER COLUMN ${columnName} DROP DEFAULT;`,
      );
    } else {
      statements.push(
        `ALTER TABLE ${qualifiedTable} ALTER COLUMN ${columnName} SET DEFAULT ${columnChange.to.default};`,
      );
    }
  }

  if (columnChange.from.nullable !== columnChange.to.nullable) {
    statements.push(
      columnChange.to.nullable
        ? `ALTER TABLE ${qualifiedTable} ALTER COLUMN ${columnName} DROP NOT NULL;`
        : `ALTER TABLE ${qualifiedTable} ALTER COLUMN ${columnName} SET NOT NULL;`,
    );
  }

  return statements;
}

function summarizeSchemaSqlWork(
  tableDiff: SchemaTableDiff,
  options: GenerateSchemaSqlOptions,
): string {
  const changeDescriptions: string[] = [];

  if (tableDiff.createTable) {
    changeDescriptions.push("create table");
  }

  if (tableDiff.dropTable) {
    changeDescriptions.push(
      options.includeDrops ? "drop table" : "drop table skipped",
    );
  }

  if (tableDiff.addColumns.length > 0) {
    changeDescriptions.push(`${tableDiff.addColumns.length} column(s) to add`);
  }

  if (tableDiff.alterColumns.length > 0) {
    changeDescriptions.push(
      `${tableDiff.alterColumns.length} column(s) to alter`,
    );
  }

  if (tableDiff.dropColumns.length > 0) {
    changeDescriptions.push(
      options.includeDrops
        ? `${tableDiff.dropColumns.length} column(s) to drop`
        : `${tableDiff.dropColumns.length} column drop(s) skipped`,
    );
  }

  if (tableDiff.primaryKeyChange) {
    changeDescriptions.push("primary key change");
  }

  return changeDescriptions.join(", ");
}

function reportProgress(
  callback: ((message: string) => void) | undefined,
  message: string,
): void {
  if (callback) {
    callback(message);
  }
}
