import {
  type DiffJson,
  type DeleteRecord,
  type InsertRecord,
  type UpdateRecord,
} from "../diff/diff-schema";
import {
  quoteIdentifier,
  quoteQualifiedTable,
  validateIdentifier,
  validateIdentifiers,
} from "../shared/identifiers";

export interface GenerateSqlOptions {
  applyInserts: boolean;
  applyUpdates: boolean;
  applyDeletes: boolean;
  transaction: boolean;
  onProgress?: (message: string) => void;
}

export interface GeneratedSqlResult {
  sql: string;
  summary: {
    inserts: number;
    updates: number;
    deletes: number;
  };
}

export function buildSqlOutputPath(inputPath: string): string {
  return inputPath.endsWith(".json")
    ? inputPath.replace(/\.json$/i, ".sql")
    : `${inputPath}.sql`;
}

export function generateSqlScript(
  diff: DiffJson,
  options: GenerateSqlOptions,
): GeneratedSqlResult {
  const lines: string[] = [];
  const summary = {
    inserts: 0,
    updates: 0,
    deletes: 0,
  };

  lines.push("-- Generated by frg-data-diff");
  lines.push(`-- Diff format: ${diff.format}`);
  lines.push(`-- Generated at: ${diff.generatedAt}`);
  lines.push(`-- Source schema: ${diff.source.schema}`);
  lines.push(`-- Destination schema: ${diff.dest.schema}`);

  if (options.transaction) {
    lines.push("");
    lines.push("BEGIN;");
  }

  reportProgress(
    options.onProgress,
    `Generating data SQL for ${diff.tables.length} table diff(s)...`,
  );

  for (const [tableIndex, tableDiff] of diff.tables.entries()) {
    const progressLabel = `[data-sql ${tableIndex + 1}/${diff.tables.length}] ${tableDiff.schema}.${tableDiff.table}`;

    reportProgress(
      options.onProgress,
      `${progressLabel}: ${summarizeDataSqlWork(tableDiff, options)}`,
    );

    validateIdentifier(tableDiff.schema, "schema name");
    validateIdentifier(tableDiff.table, "table name");
    validateIdentifiers(tableDiff.primaryKey, "primary key column");

    const statements: string[] = [];

    if (options.applyInserts) {
      for (const insert of tableDiff.inserts) {
        statements.push(
          buildInsertStatement(
            tableDiff.schema,
            tableDiff.table,
            insert,
            tableDiff.columnTypes,
          ),
        );
        summary.inserts++;
      }
    }

    if (options.applyUpdates) {
      for (const update of tableDiff.updates) {
        statements.push(
          buildUpdateStatement(
            tableDiff.schema,
            tableDiff.table,
            tableDiff.primaryKey,
            update,
            tableDiff.columnTypes,
          ),
        );
        summary.updates++;
      }
    }

    if (options.applyDeletes) {
      for (const del of tableDiff.deletes) {
        statements.push(
          buildDeleteStatement(
            tableDiff.schema,
            tableDiff.table,
            tableDiff.primaryKey,
            del,
            tableDiff.columnTypes,
          ),
        );
        summary.deletes++;
      }
    }

    if (statements.length === 0) {
      reportProgress(
        options.onProgress,
        `${progressLabel}: no SQL statements generated`,
      );
      continue;
    }

    reportProgress(
      options.onProgress,
      `${progressLabel}: generated ${statements.length} SQL statement(s)`,
    );

    lines.push("");
    lines.push(`-- ${tableDiff.schema}.${tableDiff.table}`);
    lines.push(...statements);
  }

  if (options.transaction) {
    lines.push("");
    lines.push("COMMIT;");
  }

  lines.push("");

  return {
    sql: lines.join("\n"),
    summary,
  };
}

function buildInsertStatement(
  schema: string,
  table: string,
  record: InsertRecord,
  columnTypes?: Record<string, string>,
): string {
  const columns = Object.keys(record.row);
  validateIdentifiers(columns, "insert column");
  const qualifiedTable = quoteQualifiedTable(schema, table);
  const quotedColumns = columns.map(quoteIdentifier).join(", ");
  const values = columns
    .map((column) =>
      toSqlLiteral(record.row[column], "value", column, columnTypes?.[column]),
    )
    .join(", ");
  return `INSERT INTO ${qualifiedTable} (${quotedColumns}) VALUES (${values});`;
}

function buildUpdateStatement(
  schema: string,
  table: string,
  pkColumns: string[],
  record: UpdateRecord,
  columnTypes?: Record<string, string>,
): string {
  const setColumns = Object.keys(record.changes);
  validateIdentifiers(setColumns, "update column");
  const qualifiedTable = quoteQualifiedTable(schema, table);

  const setClause = setColumns
    .map(
      (column) =>
        `${quoteIdentifier(column)} = ${toSqlLiteral(record.changes[column].to, "value", column, columnTypes?.[column])}`,
    )
    .join(", ");

  const pkWhere = buildSqlWhereClause(
    pkColumns.map((column) => [column, record.pk[column]] as const),
    "pk",
    columnTypes,
  );

  const guardWhere = buildSqlWhereClause(
    Object.entries(record.guard).filter(
      ([column]) => !pkColumns.includes(column),
    ),
    "guard",
    columnTypes,
  );

  const whereClause = guardWhere ? `${pkWhere} AND ${guardWhere}` : pkWhere;
  return `UPDATE ${qualifiedTable} SET ${setClause} WHERE ${whereClause};`;
}

function buildDeleteStatement(
  schema: string,
  table: string,
  pkColumns: string[],
  record: DeleteRecord,
  columnTypes?: Record<string, string>,
): string {
  const qualifiedTable = quoteQualifiedTable(schema, table);

  const pkWhere = buildSqlWhereClause(
    pkColumns.map((column) => [column, record.pk[column]] as const),
    "pk",
    columnTypes,
  );

  const guardWhere = buildSqlWhereClause(
    Object.entries(record.guard).filter(
      ([column]) => !pkColumns.includes(column),
    ),
    "guard",
    columnTypes,
  );

  const whereClause = guardWhere ? `${pkWhere} AND ${guardWhere}` : pkWhere;
  return `DELETE FROM ${qualifiedTable} WHERE ${whereClause};`;
}

function buildSqlWhereClause(
  entries: ReadonlyArray<readonly [string, unknown]>,
  mode: "pk" | "guard",
  columnTypes?: Record<string, string>,
): string {
  const filteredEntries = entries.filter(
    ([column, value]) =>
      !(mode === "guard" && shouldSkipPointGuard(column, value)),
  );
  validateIdentifiers(
    filteredEntries.map(([column]) => column),
    `${mode} column`,
  );
  return filteredEntries
    .map(([column, value]) => {
      const columnType = columnTypes?.[column];
      const useJsonbComparison =
        mode === "guard" &&
        (isJsonColumnType(columnType) || (!columnType && isPlainObject(value)));
      const left = useJsonbComparison
        ? `${quoteIdentifier(column)}::jsonb`
        : quoteIdentifier(column);
      return `${left} IS NOT DISTINCT FROM ${toSqlLiteral(
        value,
        useJsonbComparison ? "json_guard" : "value",
        column,
        columnType,
      )}`;
    })
    .join(" AND ");
}

function toSqlLiteral(
  value: unknown,
  mode: "value" | "json_guard",
  columnName?: string,
  columnType?: string,
): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (isJsonColumnType(columnType)) {
    const jsonLiteral = sqlStringLiteral(JSON.stringify(value));
    if (mode === "json_guard") {
      return `${jsonLiteral}::jsonb`;
    }
    return `${jsonLiteral}::${columnType}`;
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error(`Cannot generate SQL for non-finite number: ${value}`);
    }
    return String(value);
  }

  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE";
  }

  if (typeof value === "string") {
    const literal = sqlStringLiteral(value);
    if (columnName && looksLikePointValue(columnName, value)) {
      return `${literal}::point`;
    }
    return mode === "json_guard" ? `${literal}::jsonb` : literal;
  }

  if (Array.isArray(value)) {
    return sqlStringLiteral(buildPostgresArrayLiteral(value));
  }

  if (isByteaValue(value)) {
    return `decode(${sqlStringLiteral(value.$value)}, 'base64')`;
  }

  if (isPlainObject(value)) {
    const literal = sqlStringLiteral(JSON.stringify(value));
    return mode === "json_guard" ? `${literal}::jsonb` : literal;
  }

  return sqlStringLiteral(String(value));
}

function sqlStringLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function buildPostgresArrayLiteral(values: unknown[]): string {
  return `{${values.map((value) => buildPostgresArrayElement(value)).join(",")}}`;
}

function buildPostgresArrayElement(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (Array.isArray(value)) {
    return buildPostgresArrayLiteral(value);
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error(`Cannot generate SQL for non-finite number: ${value}`);
    }
    return String(value);
  }

  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }

  if (isByteaValue(value)) {
    return quotePostgresArrayString(value.$value);
  }

  if (isPlainObject(value)) {
    return quotePostgresArrayString(JSON.stringify(value));
  }

  return quotePostgresArrayString(String(value));
}

function quotePostgresArrayString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function summarizeDataSqlWork(
  tableDiff: DiffJson["tables"][number],
  options: GenerateSqlOptions,
): string {
  const insertsToApply = options.applyInserts ? tableDiff.inserts.length : 0;
  const updatesToApply = options.applyUpdates ? tableDiff.updates.length : 0;
  const deletesToApply = options.applyDeletes ? tableDiff.deletes.length : 0;

  return `processing ${insertsToApply} insert(s), ${updatesToApply} update(s), ${deletesToApply} delete(s)`;
}

function reportProgress(
  callback: ((message: string) => void) | undefined,
  message: string,
): void {
  if (callback) {
    callback(message);
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !isByteaValue(value)
  );
}

function isByteaValue(
  value: unknown,
): value is { $type: "bytea"; $value: string } {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    (value as Record<string, unknown>)["$type"] === "bytea" &&
    typeof (value as Record<string, unknown>)["$value"] === "string"
  );
}

function looksLikePointValue(columnName: string, value: string): boolean {
  return (
    columnName.toLowerCase().includes("point") &&
    /^\(\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*\)$/.test(value)
  );
}

function shouldSkipPointGuard(columnName: string, value: unknown): boolean {
  return typeof value === "string" && looksLikePointValue(columnName, value);
}

function isJsonColumnType(columnType?: string): columnType is "json" | "jsonb" {
  const normalizedColumnType = columnType?.toLowerCase();
  return normalizedColumnType === "json" || normalizedColumnType === "jsonb";
}
